name: Generate Images List

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  generate-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate images.json
        run: |
          cd images
          if ls *.webp 1> /dev/null 2>&1; then
            ls -1 *.webp | jq -R -s -c 'split("\n") | map(select(length > 0))' > images.json
          else
            echo '[]' > images.json
          fi
          echo "Generated images.json:"
          cat images.json
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add images/images.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update images.json [skip ci]" && git push)
