name: Generate Images List

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  generate-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate images.json
        run: |
          cd images
          ls -1 *.webp 2>/dev/null | jq -R -s -c 'split("\n") | map(select(length > 0))' > images.json
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add images/images.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update images.json [skip ci]" && git push)
